# we can use this same cluster issuer in all namespaces
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
# Use this name reference in the ingress annotations to reference this issuer
  name: http-01-production
spec:
  acme:
    email: your-email@devopsbyexample.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http-01-production-cluster-issuer
    solvers:
    # using http01 resolver challenge
      - http01:
          ingress:
            ingressClassName: external-nginx
