---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-aws-secrets
  namespace: aws-secrets-eks
spec:
  provider: aws
  parameters:
    region: eu-central-1
    # for the object name use the secret name
    # if want to parse and mount values instead of the default json object, we use jmesPath and use aws secret manager keys as path
    objects: |
      - objectName: staging/myapp-secret-v4
        objectType: secretsmanager
        jmesPath:
            - path: username
              objectAlias: myusername
            - path: password
              objectAlias: mypassword
  # to mount the secrets as env variables, we also need to create secretObjects and reference the keys
  secretObjects:
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - objectName: myusername
          key: k8s-myusername
        - objectName: mypassword
          key: k8s-mypassword
