# linking a k8s service account with the IAM role using the annotations
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp
  namespace: aws-secrets-eks
  # get this annotation from the tf output
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::424432388155:role/staging-demo-myapp-secrets
